spring:
  application:
    name: tcpsample
#  datasource:
#    url: jdbc:postgresql://localhost:5432/<changeme>
#    username: <changeme>
#    password: <changeme>

server:
  port: 8080


## Datasource
#spring.datasource.url=jdbc:mysql://localhost:3306/containerize_java_spring
#spring.datasource.username={username}
#spring.datasource.password={password}
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#spring.jpa.properties.hibernate.dialectorg.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.open-in-view=false
#spring.jpa.hibernate.ddl-auto=none
